// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiIIuUpk3oKpg4cSs3rR3T7q8A6Y3ptW8',
    appId: '1:998648013723:web:9a5d30500797d48df0f73e',
    messagingSenderId: '998648013723',
    projectId: 'progpal-b3401',
    authDomain: 'progpal-b3401.firebaseapp.com',
    storageBucket: 'progpal-b3401.appspot.com',
    measurementId: 'G-Q4ZP495K77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZGEOdxHy3E34Qg0hlJBY6SnCHoUoEyE',
    appId: '1:998648013723:android:8ad8a6a0269b486bf0f73e',
    messagingSenderId: '998648013723',
    projectId: 'progpal-b3401',
    storageBucket: 'progpal-b3401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN9tjLMtUfIj-l1bxebsU4RTTvN6qqgjE',
    appId: '1:998648013723:ios:ae6a5afd2ead258ef0f73e',
    messagingSenderId: '998648013723',
    projectId: 'progpal-b3401',
    storageBucket: 'progpal-b3401.appspot.com',
    iosBundleId: 'com.example.progpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN9tjLMtUfIj-l1bxebsU4RTTvN6qqgjE',
    appId: '1:998648013723:ios:d136fe72adcfbcc4f0f73e',
    messagingSenderId: '998648013723',
    projectId: 'progpal-b3401',
    storageBucket: 'progpal-b3401.appspot.com',
    iosBundleId: 'com.example.progpal.RunnerTests',
  );
}
